# Generated by Django 4.1.2 on 2022-10-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(upload_to="courses"),
        ),
    ]
